# Generated by Django 2.2.1 on 2019-05-28 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_TestCase_host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userid', models.IntegerField()),
                ('method', models.CharField(default='post', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user_host',
            old_name='type',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='username',
        ),
        migrations.CreateModel(
            name='user_TestCase_body',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.user_TestCase_host')),
            ],
        ),
    ]
