# Generated by Django 2.2.1 on 2019-05-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20190528_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Case_Assert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Assert', models.CharField(max_length=200)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.user_TestCase_host')),
            ],
        ),
    ]
