# Generated by Django 2.2.1 on 2019-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_user_case_assert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_host',
            name='casename',
            field=models.CharField(default='暂无名称', max_length=100),
        ),
    ]
