# Generated by Django 2.2.1 on 2019-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_user_host_casename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_body',
            name='type',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
