# Generated by Django 2.2.1 on 2019-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_user_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_body',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='user_host',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
