# Generated by Django 2.2.1 on 2019-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20190531_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_case_assert',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='user_testcase_body',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='user_testcase_host',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
