# Generated by Django 2.2.1 on 2019-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_auto_20190531_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
