# Generated by Django 2.2.1 on 2019-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_userinfo_old_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='useing',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
