# Generated by Django 2.2.1 on 2019-07-11 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_userinfo_useing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
