# Generated by Django 2.2.1 on 2019-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_userinfo_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_body',
            name='json_body',
            field=models.CharField(default='', max_length=200),
        ),
    ]
