# Generated by Django 2.2.1 on 2019-07-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_casecp_mk'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecp_mk',
            name='status',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
