# Generated by Django 2.2.1 on 2019-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0015_casecp_mk_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_case_assert',
            name='Assert',
        ),
        migrations.AddField(
            model_name='user_case_assert',
            name='Assert_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user_case_assert',
            name='Assert_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user_testcase_host',
            name='subjectionId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
