# Generated by Django 2.2.1 on 2019-08-08 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0017_user_testcase_body_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_name', models.CharField(default='', max_length=200)),
                ('becuxe_id', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
