# Generated by Django 2.0.2 on 2018-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20180731_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_host',
            name='host',
            field=models.CharField(max_length=200),
        ),
    ]
