# Generated by Django 2.0.2 on 2018-08-17 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20180731_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_host',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_host',
            name='response_body',
            field=models.TextField(default='ZZZ', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_host',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
