# Generated by Django 2.0.2 on 2018-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20180817_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_body',
            name='key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_body',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
