# Generated by Django 2.0.2 on 2018-08-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_user_host_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_body',
            old_name='host_id',
            new_name='host',
        ),
    ]
