# Generated by Django 2.0.2 on 2018-08-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_auto_20180831_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_body',
            name='request_body',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
