# Generated by Django 2.0.2 on 2018-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_user_body_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_body',
            name='key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_body',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
