# Generated by Django 2.0.2 on 2018-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_auto_20180831_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_body',
            name='request_body',
        ),
        migrations.AddField(
            model_name='user_host',
            name='request_body',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
